### ISSUE TITLE
Timestamp of message sometimes not parseable

### ISSUE THREAD

**Issue by 125m125** [125m125/ktapi-java#59]
```java
java.time.format.DateTimeParseException: Text 'Feb 6, 2019 3:42:05 AM' could not be parsed at index 0
 	at java.time.format.DateTimeFormatter.parseResolved0(Unknown Source)
 	at java.time.format.DateTimeFormatter.parse(Unknown Source)
 	at java.time.LocalDateTime.parse(Unknown Source)
 	at de._125m125.kt.ktapi.core.entities.Message.getTime(Message.java:31)
```
called from SuccessCallback of getMessages(0,10).

**Comment by 125m125** [comment]
The server used the wrong format for json-Messages. It now uses unix timestamps.
